# This is a basic workflow that is manually triggered

name: Update Dockerfile

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "* * * * *"
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  modfy_runner_version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - run: |
          CURRENT_GH_RUNNER_VERSION=$(grep -v '#' Dockerfile |grep GH_RUNNER|head -1|awk -F\" '{print $2}')
          NEW_GH_RUNNER_VERSION=$(curl -s https://api.github.com/repos/actions/runner/releases| jq '.[0].tag_name' --raw-output | cut -c2-)
          if [ "$CURRENT_GH_RUNNER_VERSION" != "$NEW_GH_RUNNER_VERSION" ]
          then
            echo "Newer runner version detected"
            sed -i -e "s/^RUN GH_RUNNER_VERSION.*$/RUN GH_RUNNER_VERSION=\"$NEW_GH_RUNNER_VERSION\"/" Dockerfile
          fi
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
